apiVersion: v1
kind: Service
metadata:
  name: laravel-application
  namespace: app
  labels:
    app: laravel-application
spec:
  type: ClusterIP
  selector:
    app: laravel-application
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
